version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.9
  pre_build:
    commands:
      # setup
      - dt=$(date '+%Y%m%d%H%M%S');
      - project_name=rythm-binance-stream
      - npm install -g aws-cdk@next
      - COMMIT_HASH=SV_$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - export IMAGE_TAG=${COMMIT_HASH:=latest}
      - IMAGE_NAME=$project_name:$IMAGE_TAG
      - aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin 919217319840.dkr.ecr.us-west-2.amazonaws.com
      - aws ecr describe-repositories --repository-names ${project_name} || aws ecr create-repository --repository-name ${project_name}
  build:
    commands:
      # service
      - cd $CODEBUILD_SRC_DIR/service
      - pip install -r requirements.txt
      - docker build -t $IMAGE_NAME .
      - docker tag $IMAGE_NAME 919217319840.dkr.ecr.us-west-2.amazonaws.com/$IMAGE_NAME
      - docker push 919217319840.dkr.ecr.us-west-2.amazonaws.com/$IMAGE_NAME

      # deployment
      # testing 1014
      - template_file_name=dev-template-$dt.yaml
      - cd $CODEBUILD_SRC_DIR/deployment/src
      - npm install
      - npm build
      - cdk synth > $template_file_name
      - aws s3 cp $template_file_name s3://build.cdk.rythm.cc/$project_name/$template_file_name
      - cdk diff -c aws-cdk:enableDiffNoFail=true
      - cdk deploy
