version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.9
  pre_build:
    commands:
      # setup
      - dt=$(date '+%Y%m%d%H%M%S');
      - project_name=pipeline
      - npm install -g aws-cdk@next
      - export COMMIT_HASH=SV_$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - export IMAGE_TAG=${COMMIT_HASH:=latest}
      - aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin 919217319840.dkr.ecr.us-west-2.amazonaws.com
      - REPO_NAME=rythm-binance-stream
      - aws ecr describe-repositories --repository-names ${REPO_NAME} || aws ecr create-repository --repository-name ${REPO_NAME}
  build:
    commands:
      # service
      - cd $CODEBUILD_SRC_DIR/service
      - pip install -r requirements.txt
      - docker build -t rythm/binance-stream:$IMAGE_TAG .

      # deployment
      - template_file_name=dev-template-$dt.yaml
      - cd $CODEBUILD_SRC_DIR/deployment/src
      - npm install
      - npm build
      - cdk synth > $template_file_name
      - aws s3 cp $template_file_name s3://build.cdk.rythm.cc/$project_name/$template_file_name
      - cdk diff -c aws-cdk:enableDiffNoFail=true
      - cdk deploy
